def main():
    # List manipulation
    lstInput = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    print(f"The list is: {lstInput}")
    
    print(f"1.  {lstInput[0]} is the first element of the list")
    print(f"2.  {lstInput[-1]} is the last element of the list")
    print(f"3.  {lstInput[3:]} is the list without the first three elements")
    print(f"4.  {lstInput[:5]} is the first five elements of the list")
    print(f"5.  {lstInput[-6:]} is the last six elements of the list")
    print(f"6.  {lstInput[:-9]} is the list without the last nine elements")
    print(f"7.  {lstInput[3:8]} is the elements between the 4th and 9th elements")
    print(f"8.  {lstInput[::2]} is every other element of the list")
    print(f"9.  {lstInput[::-1]} is the list in reverse order")
    print("10.  ",lstInput[0:2] + lstInput[7:15] , " is the first two elements and the elements between the 8th and 16th elements")
    print(f"11.  {lstInput.append(11)} is the list with 11 appended to the end")
    print(f"12.  {lstInput.pop()} is the list with the last element removed")
    print(f"13.  {lstInput.insert(5, 5.5)} is the list with 5.5 inserted at index 5")
    print(f"14.  {lstInput.remove(5.5)} is the list with the first occurrence of 5.5 removed")
    print(f"15.  {lstInput.index(7)} is the index of the first occurrence of 7")
    print(f"16.  {lstInput.count(7)} is the number of occurrences of 7")
    print(f"17.  {lstInput.reverse()} is the list in reverse order")
    print(f"18.  {lstInput.sort()} is the list sorted in ascending order")
    print(f"19.  {lstInput.sort(reverse=True)} is the list sorted in descending order")
    print(f"20.  {lstInput.clear()} is the list cleared")
    print("21.  use 'in' to check if an element is in the list")
    print("22.  use 'not in' to check if an element is not in the list")
    print("23.  use 'len(list)' to get the number of elements in the list")
    print("24.  use 'max(list)' to get the maximum element in the list")
    print("25.  use 'min(list)' to get the minimum element in the list")
    print("26.  use 'sum(list)' to get the sum of the elements in the list")
    print("27.  use 'list.copy()' to create a shallow copy of the list")
    print("28.  use 'list.extend([new elements])' to add new elements to the list")
    print("29.  use 'list.remove(element)' to remove the first occurrence of an element from the list")
    print("30.  use 'list.clear()' to remove all elements from the list")
    print("31.  use 'list.pop()' to remove and return the last element from the list")
    print("32.  use 'list.pop(index)' to remove and return the element at the specified index from the list")
    print("33.  use 'list.insert(index, element)' to insert an element at the specified index in the list")
    print("34.  use 'list.index(element)' to get the index of the first occurrence of an element in the list")
    print("35.  use 'list.count(element)' to get the number of occurrences of an element in the list")
    print("36.  use 'list.reverse()' to reverse the elements of the list")
    print("37.  use 'list.sort()' to sort the elements of the list in ascending order")
    print("38.  use 'list.sort(reverse=True)' to sort the elements of the list in descending order")

main()